### ISSUE TITLE
Adding a new view when the previuos one is not finished to animate

### ISSUE THREAD

**Issue by rprunskas** [R3PI/Defrag#30]
Hello, I would be nice if this library would be able to add a view to the queue(or force to add it to the top) and display it once traversing state is idle, I've done a workaround to solve this. 

Also I think this library is missing feature to turn off animation easily.

java.lang.IllegalStateException: ViewStack is currently traversing
                                                                at com.solera.defrag.ViewStack.setTraversingState(ViewStack.java:149)
                                                                at com.solera.defrag.ViewStack.pushWithParameters(ViewStack.java:212)
                                                                at com.solera.defrag.ViewStack.push(ViewStack.java:201)

Edit: I noticed ViewStackUtils class which contains similar solution to my workaround. So maybe I only missing traversals without animation.

**Comment by tomjhall** [comment]
Hi. Yes, 1.0 release should ViewStackUtils class should allow you push/pop/replace a view after the current traversal has completed.
You are right - we should have a general capability to add/remove a general default animation handler (which would allow you to turn off traversal animations, too). I've raised a seperate issue (#31) around this.

**Comment by tomjhall** [comment]
Using AnimationHandler (in v1.1.0) it should be pretty easy to turn off transition animations (or create custom animations) - just return null from the createAnimation callback there will be no animation.

Using ViewStackUtils you should be able to push a view while it is transitioning - avoiding the currently traversing exception.
